### ISSUE TITLE
WTF Exploration Minecraft:Torch is Registered Twice

### ISSUE THREAD

**Issue by PB5011** [whatthedrunk/allthemods#115]
Issue Description:
WTF Exploration Minecraft:Torch is Registered Twice
Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Can't connect to game with error "Minecraft:Torch is registered Twice...". 
What you expected to happen:
Connect to Server
Steps to reproduce:

1.Update Server from 1.10 to 1.12
2.Try to connect
3.
...

Version of All the Mods:
All updated to modpack version 1.12
Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by WhiskyTangoFawks** [comment]
You're referencing an outdated config setup, in the latest version of the mod the options have been changed- I suggest deleting the config and allowing it to reset to the new default as an initial step if you're having issues (once the mod is out of Beta testing, this sort of changes aren't going to occur).  Also, make sure you're on at least forge 12.18.1.2050 (which is what the mod is built against in the latest release).  If you're using either an earlier or a later version- try moving to that (if this fixes it, let me know, because the solution is for me to build it against the newer version of forge).

Possible conflicts: Any other mod that modifies the behaviour of torches - if it's a conflict, the work around is to disable my torch modifications, which can be done so in the gameplay config.

**Comment by nimda79** [comment]
The Mod Pack is on Forge 12.18.1.2065 (the most current recommended version of forge) not 2050. Tested with a fresh client install and same issue occurs to the updated server. 

Internal Exception: Java.lang.IllegalArgumentException: The object class wtf.core.blocks.BlockWTFTorch (minecraft:torch) cannot be added to the registry. It is already being used as a substitute for minecraft:torch

**Comment by Carrots4U** [comment]
We are working on a hotfix right now so please be patient :) Hopefully it will be out within the hour.

**Comment by nimda79** [comment]
TY Carrots4U!

**Comment by WhiskyTangoFawks** [comment]
Another WTF Expedition user has reported that downgrading the forge version solves the issue with WTF Expedition- which means the final fix is the mod author (me, if that wasn't clear) releasing a version built on 2065 instead of 2050.  With any luck I can have a new version of the mod out by the end of the week, but there are a few changes still in alpha testing that I need to get through before I can do so.

**Comment by radiocrack** [comment]
using pack 1.10.2 R13
which downgraded both client and server to 2050. Deleted WTFGameplay.cfg on client and server to allow recreate.  Restarted both client and server. Still crashing on client when joining a server.

**Comment by radiocrack** [comment]
Retested with latest 1.13b
Fixed

Thanks for the quick fix Whisky.  Good to see Mod authors and ModPack authors working together.

**Comment by nimda79** [comment]
Works for me as well! Appreciate it!
