### ISSUE TITLE
Cant Pipe from / to EnderChest

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#12]
Maybe a forge issue?

**Comment by ZiggyAdventures** [comment]
Correct: All The Mods v3.5 and v3.6 are using forge 1780 accidentally since forge submitted it erroneously to 1.9.4. This can cause crashes(For example opening EnderIO machines or loading crashes) As a workaround, install forge 1976. WhatTheDrunk said he will fix it in tomorrow's update. Sorry for the inconvenience.

**Comment by Carrots4U** [comment]
Vanilla Enderchests cannot be piped in/out of. You have to use the Enderchest from the mod "Ender Thing"
