### ISSUE TITLE
Waila problems continue (Drac Evolution)

### ISSUE THREAD

**Issue by TomuTails** [whatthedrunk/allthemods#222]
Issue Description: Basically, I placed some dirt on the wall with Draconic Evolution (Using the built in hotkey default bound to P.

What happens: Instantaneous freeze and crash.

What you expected to happen:

Steps to reproduce:
1. Rebind all conflicting keys, use Draconic Evolution 'place item in world' on any wall, any surface.
2. Look at the item on said wall.
3. Crash, presumably.

Version of All the Mods:1.34

Added mods (Optifine, Fastcraft, etc.): None

**Comment by TomuTails** [comment]
For reference: https://bitbucket.org/ProfMobius/waila/issues/284/waila-crash-on-draconic-evolution-placed#comment-None

**Comment by RealGrep** [comment]
I wish you much luck in getting anything fixed in Waila. It's fairly buggy, hasn't been updated in a long time, and is basically unmaintained at this point. I'm surprised packs still include it at all, to be honest. I had enough issues with it, including a crash loop, that haven't been fixed in probably 6 months or more.

Not putting down the author here, of course, he owes us nothing at all, and I thank him for all his work on it. But I really suggest packs move away from Waila, as there are good alternatives available that are actively maintained.

**Comment by TomuTails** [comment]
Can we nudge that along to the pack creators perhaps? I much prefer Waila but not if this kind of stuff is going to keep happening.

**Comment by DietmarKrause** [comment]
yes, the one probe is an alternative, isnt it?

**Comment by ZiggyAdventures** [comment]
ProfMobious the owner of Waila now works for Mojang, so updates will probably not come and it's showing its age. The one probe is an alternative however it's laggy for players with bad connections on servers as it queries the server for each block you look at.

**Comment by RealGrep** [comment]
Hm, if Waila is less laggy on a slower connection, perhaps there's something @McJty can do to help that situation? Not sure what Waila does differently, there. Even if not, it's at least stable and maintained, anyway.

**Comment by McJty** [comment]
WAILA is client side. TOP is server side. But TOP does show basic info when the server side information is late so you can still see the basic info. The difference is that with TOP it has to wait until the server sends the info
