### ISSUE TITLE
Game crash on item harvest

### ISSUE THREAD

**Issue by syntaxjedi** [whatthedrunk/allthemods#275]
Issue Description: The game screen turns blue and crashes when harvesting Basic Universal Cable (mekanism). It only seems to happen in survival, when I switch to creative I can remove the cable with no problems.

Version of All the Mods: 1.41

Added mods (Optifine, Fastcraft, etc.): none

 [logfile](http://pastebin.com/i1d9pUK6)

**Comment by Oaurn** [comment]
When you say "Harvest" are you referring to breaking it with a pick?  Because that definitely used to cause crashes in the past.   Mekanism has it's own "Wrench" called a Configurator.   Using the configurator in wrench mode will instantly pick up the cables so it might be a good option to make one of those for Mekanism stuff.

**Comment by syntaxjedi** [comment]
That seems to work thanks.
