### ISSUE TITLE
how can u fly please add in new update

### ISSUE THREAD

**Issue by DaFuJosh** [whatthedrunk/allthemods#278]
Issue Description:

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

What you expected to happen:

Steps to reproduce:

1.[1.10.2] baublesstuff-2.0.11
2.ChestTransporter-1.10.2-2.5.4
3.SimplyJetpacks2-1.10.2-2.0.3.14
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by DnTheMn** [comment]
there is a number of ways to fly draconic armor, ring of flight (ex2) ,bat wings and quantum armor all give creative filght as for baubles stuff we had it in the pack a long time ago and removed it because it was too op. for moving chests we have the moving wand or cardboard boxes so its not needed.
