### ISSUE TITLE
[v.149] mekanism metallurgic infuser issue

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#316]
Issue Description:
The metallurgic infuser seems not to work constantly  . At first i could not make enriched iron (i want to make steel), at first normal coal seemed not to work (coal secondary, iron ingot primary input). i put in compressed coal, then suddenly it worked, after that normal coal worked too,.... i am confused. And: redstone and osmium seemed not to work either.. (to make the basic circuit). After a while waiting it worked. The block is connected to a enderio capacitor via conduits, the buffer of energy is full, redstone signal ignored, and the block is switched to RF. The block was working before the last update. Others have seen problems here too. It is a single player survival world. No crash, no error message
What happens:

What you expected to happen: get enriched iron with coal and iron ingot. 

Steps to reproduce:

1.Build a metallurgic infuser
2.connect to basic capacitor from enderio using conduits
3.try to make enriched iron using coal and iron ingot, Try other recipes (redstone/osmium after clearing the buffer) and go back to coal / iron. At some time nothing will work from one moment on
...

Version of All the Mods:1.49

Added mods (Optifine, Fastcraft, etc.):

1.nothing
2.
3.
...

**Comment by ClaireVailo** [comment]
Yes Finally, I have been having this issue on a small private server since 1.49.  I found for me, it's just the Metallurgic Infuser that is causing issues I can get everything else to work.  I finally saw your post this morning and was, unfortunately, happy that someone else had the issue haha.  I just hope it gets fixed soon.  I tried seeking help in the all the mods chat through curse but everyone thought I was crazy and no one had the same issue. 

What happened for me: 
Upgraded to 1.49, still could make stuff in the metallurgic infuser I.E steel/enriched alloy by hand no problem.  I started using refined storage and set up automation of steel, everything was working smoothly.  About an hour later I was setting up automation for enriched alloy and refined alloy.  I was able to make about 8 enriched alloy with the automation process and I made few refined with those and then about 5 minutes later I needed more as I was crafting Lasers and parts to the reactor.  When I called for it to be crafted I waited and checked the screen everything was working except enriched alloy, so I thought I messed up crafting somehow but I knew I made some already, so I go start messing with the pipes trying to put in buffers for the items thinking maybe it was refined storage causing the issue, then I try doing it by hand and the metallurgic infuser starts acting like it doesn't have a pattern that involves Iron.  I can not shift click iron into the infuser, Only force drag it where it does nothing.  I tried it with carbon and Redstone and nothing seemed to work.  
At this point I checked my steel automation and noticed everything was working except the enriched iron portion, which I had working about an hour ago.  I did not log off my server at any point during stuff stopping.  I then tried to make higher version by hand and noticed the refined alloy didnt work, but steel dust did.  So I was just like great whatever.  I restarted the server hoping this might fix it and when I got on again.  Nothing worked.  

Later that same day:
Now for another twist, Later that night when I was setting up some completely different part to my automated factory with refined storage, I saw that enriched iron had started crafting on its own again... (I have it set up to always have 100 in the system and on down the line to always have 200 steel in the system that way I'm not waiting all the time for something like steel.)  I went over took a look and it was working so I immediately went over tried to make an enriched alloy again with iron in Redstone, It did not work.  I returned to the enriched iron to find it had stopped again.  I don't know if this piece of information makes a difference but thought I would let you know.

To reproduce my error:
1. Try to make an enriched alloy either by hand/ with refined storage/enderio conduits.
2. All metallurgic infusers break.
3. overtime they start up again unless its enriched alloy.
4. I have not found anything else that breaks them all by trying to craft except this one.

I do not have other mods installed with my modpack.  I am using version 1.49.

Thanks for reading my giant wall of text recap!
I hope something from it helps.

**Comment by DietmarKrause** [comment]
>  I then tried to make higher version by hand and noticed the refined alloy didnt work, but steel dust did. So I was just like great whatever. I restarted the server hoping this might fix it and when I got on again. Nothing worked.

exactly. Sometime it works sometimes not. Suggestion; there was a "Ram saving" mod added to 1.49. Perhaps this is casing the problem?

**Comment by DietmarKrause** [comment]
Now someone is reporting the same issue with enderios sag mill. Sometime it is working, sometimes not (in that case draconic ore). There is a mod interaction i believe.

**Comment by ClaireVailo** [comment]
Yeah That someone is me again.  So I posted 2 days ago my issue with the recipes with the infuser. I didn't change anything at all and the next day I got on the server i noticed in my factory that they started working again.  So I was just meh about it. 
New Issue sorta the same:
So we updated to 1.5 the moment it came out hoping we would never have the issue again thinking maybe a mod updated or something.  The infusers have worked fine, have not seen anymore issues.  But I went about setting up a void miner and now I'm getting draconic ore so I put it through a Sag mill and get the dust and set it all up to work with my automation.  I make probably a good 200-300 ingots this way and then it broke.  The sag mill would not accept draconic ore.  None.  I do not know how to duplicate this.  I have tried to fix it and I have tried to get the infusers to break again.  It just happens... randomly.  I have not noticed anything else broken again.

**Comment by ClaireVailo** [comment]
Test: So per Dietmar's suggestion thinking it was a ram saving mod FoamFix maybe interacting, which would be confusing if it was but that was one of the new things added from 1.48 to 1.49.  I removed it from my server and client.  I got on and tried to put draconic ore in sag mill and it is still broken. So this did not fix it.

**Comment by DietmarKrause** [comment]
problem is not there any more in newer versions of the pack. It seems issue can be closed
